services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    Sidus\UserBundle\Action\Admin\:
        resource: '../../Action/Admin/'
        tags:
            - controller.service_arguments
