services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $userProvider: '@Sidus\UserBundle\Security\UserProvider'
            $hierarchy: '%security.role_hierarchy.roles%'

    Sidus\UserBundle\:
        resource: '../../'
        exclude: '../../{Debug,DependencyInjection,Entity,Model,Mailer,Action}'

    security.role_hierarchy:
        alias: Sidus\UserBundle\Security\Core\Role\RoleHierarchy

    Sidus\UserBundle\Action\:
        resource: '../../Action/'
        exclude: '../../Action/Admin'
        tags:
            - controller.service_arguments
