services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $userProvider: '@Sidus\UserBundle\Security\UserProvider'
            $hierarchy: '%security.role_hierarchy.roles%'

    Sidus\UserBundle\:
        resource: '../../'
        exclude: '../../{Debug,DependencyInjection,Entity,Model,Mailer}'

    security.role_hierarchy:
        alias: Sidus\UserBundle\Security\Core\Role\RoleHierarchy
