Sidus\UserBundle\Entity\User:
    constraints:
        -   Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
                fields: identifier
                errorPath: identifier
        -   Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
                fields: email
                errorPath: email
                message: sidus.admin.user.form.email.already_used
    properties:
        email:
            -   NotBlank:
                    message: sidus.admin.user.form.email.blank
            -   Length:
                    max: 255
                    maxMessage: sidus.admin.user.form.email.long
            -   Email:
                    message: sidus.admin.user.form.email.invalid
        password:
            -   NotBlank:
                    message: sidus.admin.user.form.password.blank
                    groups: [ 'Registration', 'ResetPassword', 'ChangePassword' ]
            -   Length:
                    min: 6
                    minMessage: sidus.admin.user.form.password.short
                    groups: [ 'Registration', 'ResetPassword', 'ChangePassword' ]

Sidus\UserBundle\Entity\Group:
    properties:
        name:
            -   NotBlank:
                    message: sidus.admin.group.form.name.blank
            -   Length:
                    min: 2
                    minMessage: sidus.admin.group.form.name.short
                    max: 255
                    maxMessage: sidus.admin.group.form.name.long
